[package]
name = "kafka-consumer-rust"
version = "0.1.0"
edition = "2023"
authors = ["Antonio Masotti"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9.0"
